// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spotify.Models;

#nullable disable

namespace Spotify.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220909234642_InitialMigrate")]
    partial class InitialMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Spotify.Models.Reggaeton", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Spotify")
                        .HasColumnType("longtext");

                    b.Property<string>("artista")
                        .HasColumnType("longtext");

                    b.Property<string>("cancion")
                        .HasColumnType("longtext");

                    b.Property<string>("color")
                        .HasColumnType("longtext");

                    b.Property<string>("imgPrincipal")
                        .HasColumnType("longtext");

                    b.Property<string>("lanzamiento")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Reggaetons");
                });
#pragma warning restore 612, 618
        }
    }
}
